version: '3.8'
services:
  diamond:
    image: iramya/daimondbox:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  circle:
    image: iramya/circlebox:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
 
