version: '3.8'
services:
  diamond:
    image: iramya/daimondbox:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
  circle:
    image: iramya/circlebox:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
 
